---

name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

#    - name: Install TeX Live Full
#      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Install TeX Live Essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-base \
          latexmk

    - name: Add timestamp to PDF
      run: |
        TIMESTAMP=$(date +"%Y_%m_%d-%H%M%S")
        mv main.pdf "elec4402-formula-sheet_$TIMESTAMP.pdf"
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: elec4402-formula-sheet_${{ github.ref }}.pdf
        path: elec4402-formula-sheet_${{ github.ref }}.pdf
        if-no-files-found: error

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: elec4402-formula-sheet_${{ github.ref }}.pdf
        asset_name: elec4402-formula-sheet_${{ github.ref }}.pdf
        asset_content_type: application/pdf
