name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

#    - name: Install TeX Live Full
#      run: sudo apt-get update && sudo apt-get install -y texlive-full

#    - name: Install TeX Live Essentials
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y \
#          texlive-latex-base \
#          latexmk

    - name: make fake file
      run: |
        echo "HELLO" > main.pdf

    - name: Add timestamp to PDF
      run: |
        TIMESTAMP=$(date +"%Y_%m_%d-%H:%M:%S")
        mv main.pdf "elec4402-formula-sheet_$TIMESTAMP.pdf"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: elec4402-formula-sheet_$TIMESTAMP.pdf
        path: elec4402-formula-sheet_$TIMESTAMP.pdf
        if-no-files-found: error
